FROM registry.redhat.io/ubi9/ubi:9.7-1764794285 AS builder

WORKDIR /app

RUN INSTALL_PKGS="\
        gzip \
        " && \
    yum -y --setopt=tsflags=nodocs --setopt=skip_missing_names_on_install=False install $INSTALL_PKGS && \
    yum -y update && \
    yum -y clean all

COPY start.sh /app/start.sh

# Fetch QEMU artifact from cachi2 prefetch
RUN cp /cachi2/output/deps/generic/rhcos-qemu.$(uname -m).qcow2.gz .
RUN gunzip rhcos-qemu.$(uname -m).qcow2.gz

FROM registry.redhat.io/ubi8/ubi:8.10-1752733233

LABEL com.redhat.component="quay-builder-qemu-rhcos-container"
LABEL name="quay/quay-builder-qemu-rhcos-rhel8"
LABEL io.k8s.display-name="Red Hat Quay - Builder QEMU RHCOS"
LABEL io.k8s.description="Red Hat Quay - Builder QEMU RHCOS"
LABEL io.openshift.tags="quay"
LABEL summary="Red Hat Quay - Builder QEMU RHCOS"
LABEL description="Red Hat Quay - Builder QEMU RHCOS"
LABEL cpe="cpe:/a:redhat:quay:3.17::el9"
LABEL vendor="Red Hat, Inc."
LABEL distribution-scope="restricted"
LABEL url="https://docs.redhat.com/en/documentation/red_hat_quay"
LABEL maintainer="support@redhat.com"

RUN mkdir -p /userdata
WORKDIR /userdata

COPY --from=builder /app/rhcos-qemu.*.qcow2 /userdata/coreos_production_qemu_image.qcow2
COPY --from=builder /app/start.sh /userdata/start.sh

RUN INSTALL_PKGS="\
        openssh-clients \
        qemu-kvm \
        libgcrypt-devel \
        " && \
    yum -y --setopt=tsflags=nodocs --setopt=skip_missing_names_on_install=False install $INSTALL_PKGS && \
    yum -y update && \
    yum -y clean all

RUN chgrp -R 0 /userdata && \
    chmod -R g=u /userdata

ENTRYPOINT ["/bin/bash", "/userdata/start.sh"]
